AWSTemplateFormatVersion: 2010-09-09
Description: Provisions a VPC endpoint for DynamoDB and demonstrates the use of the same

Resources:
  subnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId:
        Ref: routeTable
      SubnetId:
        Ref: privateSubnet
  routeTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VpcId
  privateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VpcId
      CidrBlock:
        Ref: SubnetCidrBlock

Parameters:
  VpcId:
    Description: Id for VPC
    Type: AWS::EC2::VPC::Id
  SubnetCidrBlock:
    Description: CIDR Block to assign to the subnet
    Type: String
    Default: 172.31.192.0/28

Mappings:
  RegionMap:
    ap-south-1:
      AMI: ami-47205e28
    us-east-1:
      AMI: ami-a4c7edb2

